version: '2.2'

services:
  mysql-db:
    image: mysql:5.7.21
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    networks:
      - intranet
    ports:
      - "3306:3306"  # optionnel

networks:
  intranet:
    external: true
